repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/Zac-HD/shed
  rev: 0.10.8
  hooks:
    - id: shed
   # args: [--refactor, --py39-plus]
      types_or: [python, pyi, markdown, rst]
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      additional_dependencies: [tomli]
      args: [--in-place]
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.0.2
  hooks:
    - id: sqlfluff-lint
      args: [--dialect, bigquery,
             --ignore, templating,
             --config, .sqlfluff

      ]
      # For dbt projects, this installs the dbt "extras".
      # You will need to select the relevant dbt adapter for your dialect
      # (https://docs.getdbt.com/docs/available-adapters):
#      additional_dependencies: ['dbt-bigquery==1.4.3', 'sqlfluff-templater-dbt']
#      entry: bash -c 'exec env GOOGLE_APPLICATION_CREDENTIALS=/usr/credentials/wc-data-consolidated-gcs-user.json'
    - id: sqlfluff-fix
      # Arbitrary arguments to show an example
      args: [--dialect, bigquery,
             --ignore, templating,
             --config, .sqlfluff

          ]
#      additional_dependencies: ['dbt-bigquery==1.4.3', 'sqlfluff-templater-dbt']
#      entry: bash -c 'exec env GOOGLE_APPLICATION_CREDENTIALS=/usr/credentials/wc-data-consolidated-gcs-user.json'
