[tool.poetry]
name = "vector-databases-tutorial"
version = "0.1.0"
description = ""
authors = ["minhbui <minh.bui@wirecutter.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
